apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/lb-method: "round_robin"
  labels:
    name: myingress
spec:
  rules:
  - host: a4d3d062170364ea8ae7f0cc93c9c9d1-198739f379086363.elb.ap-southeast-1.amazonaws.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: chat-app-cluster-ip-service
            port: 
              number: 8081
